package main

const appName = "Edconv"
const version = "1.2.8"
const ffmpegDefault = "./bin/ffmpeg"
const ffprobeDefault = "./bin/ffprobe"
const ffmpegVersion = "7.1.1"
const channelsDefault = "2"
const kbps20Default = "192"
const kbps51Default = "384"
const presetAv1Default = "4"
const presetH265Default = "slow"
const crfAv1Default = "25"
const crfH265Default = "21"
const bitDefault = "8"
const widthDefault = "1920"

const aacFormat = "aac"
const eac3Format = "eac3"
const h265Format = "h265"
const av1Format = "av1"